config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  resources :muses
  resources :profiles
  resources :collabs
  resources :comments
  resources :capsules
  resources :mindmaps
  root 'profiles#new'

end

app/models/mindmap.rb
class Mindmap < ActiveRecord::Base
  belongs_to :capsule
  belongs_to :profile
  belongs_to :author
end

app/controllers/mindmaps_controller.rb
class MindmapsController < ApplicationController

  before_action :find_mindmap, only: [:show, :edit, :update, :destroy]
  before_action :find_capsule, only: [:new, :create, :update, :destroy]
  before_action :authenticate_author!

  def index
    @mindmaps = Mindmap.all.order('created_at DESC')
  end

  def new
    @mindmap = Mindmap.new
  end

  def create
    @mindmap = Mindmap.new(mindmap_params)
    if @mindmap.save
      redirect_to @mindmap , notice:"You have successfully created a Mindmap"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @mindmap.update(mindmap_params)
      redirect_to @mindmap , notice:" You have successfully updated Your Mindmap"
    else
      render 'edit'
    end
  end

  def destroy
    @mindmap.destroy
    redirect_to mindmaps_path
  end

  private



  def find_mindmap
    @mindmap = Mindmap.find_by(params[:id])
  end

  def find_capsule
    @capsule = current_author.capsules.find_by(params[:id])
  end

  def mindmap_params
    params.require(:mindmap).permit(:src, :src_purpose, :capsule_id, :profile_id)
  end
end

app/helpers/mindmaps_helper.rb
module MindmapsHelper
end

app/views/mindmaps/_form.html.erb
<div class="col-md-4 mindmap-container">
  <%= simple_form_for(@mindmap) do |f| %>
    <%= f.input :src, as: :url, class:'form-control', label: false, placeholder:"Add a URL" %>
    <%= f.input :src_purpose, as: :text, class: 'form-control', label: false,  placeholder: "Add a description to your URL"%>
    <%= f.input :capsule_id, label: false, collection: Capsule.all, default: 'Select a capsule', label_method: :title %>
    <%= f.input :profile_id, label: false, collection: Profile.all, default: 'Select a Profile ID',label_method: :profile_name %>
    <%= f.button :submit, class:'btn btn-primary' %>
    <% end %>
</div>

app/views/mindmaps/edit.html.erb
<h1>Mindmaps#edit</h1>
<p>Find me in app/views/mindmaps/edit.html.erb</p>
<%= render 'mindmaps/form' %>

app/views/mindmaps/index.html.erb
<h1>Mindmaps#index</h1>
<p>Find me in app/views/mindmaps/index.html.erb</p>
<%= link_to "Create Mindmap", new_mindmap_path %>
<%= @mindmaps.each do |mindmap| %>
  <div class="mindmap">
      <strong>Name: <%= mindmap.author.email %></strong>
      <p><%= mindmap.src %></p>
      <div class="meta">
        <%= link_to time_ago_in_words(mindmap.created_at) + " ago" , mindmap %>
        <span class="admin">
          | <%= link_to "Edit", edit_mindmap_path(mindmap) %> |
          <%= link_to "Delete", mindmap ,  method: :delete, data: {confirm: "Are you sure you want to delete this Mindmap"} %>
        </span>
      </div>
      <% end %>
  </div>

app/views/mindmaps/new.html.erb
<h1>Mindmaps#new</h1>
<p>Find me in app/views/mindmaps/new.html.erb</p>
<%= render 'mindmaps/form' %>

app/views/mindmaps/show.html.erb
<h1>Mindmaps#show</h1>
<p>Find me in app/views/mindmaps/show.html.erb</p>
<strong> <%= @mindmap.capsule.title %> </strong>
<%=  @mindmap.created_at %>
<%= @mindmap.capsule.profile.profile_name%>
<%= @mindmap.src %>
<%= @mindmap.src_purpose %>

<%= link_to 'Back', mindmaps_path %>
<%= link_to 'Edit', edit_mindmap_path %>
<%= link_to 'Delete', mindmap_path, method: :delete, data: {confirm:"Are you sure you want to Delete this resource"} %>