config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  resources :muses
  resources :profiles
  resources :collabs
  resources :comments
  resources :capsules
  resources :mindmaps
  root 'profiles#new'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :author
  has_many :mindmaps
  has_many :capsules
  before_save :profile_name

  # Steve H added a comment just to make a change


    def profile_name
      @profile_name = "#{first_name} #{last_name}"
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :find_profile, only: [ :show, :edit, :update, :destroy]
  before_action :find_mindmap
  before_action :authenticate_author!


  def index
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.author_id = current_author.id
    if @profile.save
       redirect_to @profile , notice: "You have successfully created a profile"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @profile.update_attributes(profile_params)
      redirect_to @profile
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
  end

private
  def find_mindmap
    @mindmap = Mindmap.find_by(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :about_me, :date_of_birth,
                                    :nationality, :zipcode, :state, :sexe)
  end

  def find_profile
    @profile = current_author.profile
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<div class="row">
  <div class="col-md-12" id="profile-page-form">

        <%= simple_form_for(@profile, multipart: true, class: 'form-control') do |f| %>
          <div class="col-md-3">
            <li><%= f.input :first_name,label: false, id:'form_input', placeholder:"Enter your First Name" %></li>
            <li><%= f.input :last_name,label: false, placeholder:"Enter your Last Name" %></li>
            <li><%= f.input  :sexe,label: false, placeholder:"Select a Sexe" %></li>
            <li><%= f.input :date_of_birth, id: "DOB-container",as: :date, start_year: Date.today.year - 40,
                                       end_year: Date.today.year , discard_day: false,
                                       order: [:day ,:month, :year],label: false %></li>
         </div>
         <div class="col-md-3">
          <li><%= f.input :nationality, label: false,placeholder: "Enter Your Nationality" %></<li>
          <li><%= f.input :zipcode,label: false, placeholder:"Enter your Zipcode" %></li>
          <li><%= f.input :state,label: false, placeholder:"Select a State" %></li>
         </div>

        <div class="col-md-6">
          <%= f.input :about_me, as: :text, id:"about_me",label: false, placeholder:"Add something clever after all this is an Authobiography" %>
       </div>
      <%= f.button :submit, class: "btn btn-primary", id:'mindmap-btn' %>
      <% end %>
</div>

app/views/profiles/edit.html.erb
<h2>Update Profile Info</h2>
<p>Find me in app/views/profiles/edit.html.erb</p>
<%= render 'profiles/form' %>

app/views/profiles/index.html.erb
<h1>Profiles#index</h1>
<p>Find me in app/views/profiles/index.html.erb</p>

app/views/profiles/new.html.erb
<h2>Create Your Profile</h2>

<%= render 'profiles/form' %>

app/views/profiles/show.html.erb
<h1>Profiles#show</h1>
<p>Find me in app/views/profiles/show.html.erb</p>


<%= @profile.about_me %>

<%= link_to @profile.profile_name, profile_path %>

<%= link_to "Edit Profile", edit_profile_path(current_author) %>
<%= link_to "Add New Mindmap", new_mindmap_path %>

<ul class="capsule-container">
  <% if @profile.capsules.any? %>
      <% @profile.capsules.each do |capsule| %>
      <ul class="capsule-author-info">
        <li> Author Picture </li>
        <li><%= link_to capsule.author.author_fullname, profile_path %></li>
      </ul>
        <ul class="capsule-social-data">
          <li id="capsule-title">Capsule Title: <%= capsule.title %></li>
          <li> Likes</li>
          <li> Bookmarks</li>
          <li> Comments</li>
          <li> icons </li>
          <li><%= link_to 'Delete Capsule', capsule_path, method: :delete,
             data: {confirm:"Are you sure you want to Delete this resource"} %></li>
        </ul>
      <li> Capsule Photo </li>
      <ul class="capsule-info">
        <li >Capsule About:<%= capsule.about %></li>
        <li>Capsule Purpose:<%= capsule.purpose %></li>
      </ul>
      <li> Progression Picture </li>
      <li> Collab List </li>
      <% if capsule.mindmaps.any? %>
      <ol class="profile-mindmap-container">
         <% capsule.mindmaps.each do |mindmap| %>
        Mindmap:
          <li><%= time_ago_in_words(mindmap.created_at) %><li>
          <li><%= mindmap.src %></li>
          <li><%= mindmap.src_purpose %></li>
          <%end %>
         <% else %>
         DISplay you need to make a capsule
         <% end %>
         <%= link_to 'Edit Capsule', edit_mindmap_path %>
       </ol>


    <% end %>
<% end %>
</ul>