config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  resources :muses
  resources :profiles
  resources :collabs
  resources :comments
  resources :capsules
  resources :mindmaps
  root 'profiles#new'

end

app/models/capsule.rb
class Capsule < ActiveRecord::Base
  belongs_to :author
  belongs_to :profile
  has_many :collabs
  has_many :comments, dependent: :destroy
  has_many :mindmaps, dependent: :destroy
  accepts_nested_attributes_for :mindmaps, :comments
end

app/controllers/capsules_controller.rb
class CapsulesController < ApplicationController

  before_action :find_capsule, only:[:index, :show, :edit, :update, :destroy]
  before_action :find_mindmap, only: [:index, :show, :edit, :update, :destroy]
  before_action :authenticate_author!

  def index
    @capsules = Capsule.all.order('created_at DESC')
  end

  def new
    @capsule = Capsule.new
  end

  def create
    @capsule = Capsule.new(capsule_params)
    @capsule.author_id = current_author.id
    @capsule.profile_id = current_author.profile.id # Check with Steve if i should set this equal to current_author.profile.id
    if @capsule.save
      redirect_to @capsule , notice:" Your Capsule was successfully created"
    else
     render 'new'
    end
  end

  def edit
  end

  def update
    if @capsule.update(capsule_params)
      redirect_to @capsule , notice: "You have successfully Updated your Capsule"
    else
      render 'edit'
    end
  end

  def show
    @mindmap = @capsule.mindmaps.find_by(params[:id])
  end

  def destroy
    @capsule.destroy
    redirect_to root_path
  end

  private


  def find_mindmap
    @mindmap = Mindmap.find_by(params[:id])
  end

  def find_capsule
    @capsule = Capsule.find_by(params[:id])
  end

  def capsule_params
    params.require(:capsule).permit(:title, :about, :purpose, :profile_id,  mindmaps_attributes: [ :src, :src_purpose, :id])
  end
end

app/helpers/capsules_helper.rb
module CapsulesHelper
end

app/views/capsules/_form.html.erb
<div class="row">
  <div class="col-md-12">
          <div class="col-md-4 well">
          input the capsule image uploader
          </div>
          <div class="col-md-4 container">
                  <%= simple_form_for(@capsule , multipart: true) do |f| %>
            <ul id="capsule-form-input">
              <li><%= f.input :title, class:'form-control', label: false, placeholder: "Capsule Title"%></li>
              <li><%= f.input :about, as: :text, class: 'form-control', label: false, placeholder: "Capsule About Info" %></li>
              <li><%= f.input :purpose, as: :text, class: 'form-control', label: false, placeholder: "Capsule Purpose Info" %></li>
              <li><%= f.input :profile_id, collection: Profile.all, label: false, label_method: :profile_name %></li>
              <li><%= f.button :submit, class:'btn btn-primary' %></li>
            </ul>
          <% end %>
        </div>
  </div>
</div>

app/views/capsules/edit.html.erb
<h1> Edit Page </h1>

<%= render 'capsules/form' %>

app/views/capsules/index.html.erb
<h1> Index Page </h1>
<%= link_to "Create New Capsule", new_capsule_path %>
<%= link_to "Create Mindmap", new_mindmap_path %>
<%= @capsules.each do |capsule| %>
  <h2><%=  capsule.title %></h2>
  <%= capsule.about %>
  <strong><%= capsule.purpose %></strong>
  <%= link_to capsule.title %>

<% end %>

app/views/capsules/new.html.erb
 <h1> Create new Capsule </h1>

 <%= render 'capsules/form' %>
 

app/views/capsules/show.html.erb
<div class="col-md-12", id="capsule-show-container-master">
  <div class="col-md-2 well">
    <%=  @capsule.title %>
  </div>

  <div class="col-md-6", id="capsule-show-container">
    <div class="col-md-2", id="capsule-show-about">
      <%= @capsule.about %>
    </div>
    <div class="col-md-2", id="capsule-show-purpose">
      <%= @capsule.purpose %>
    </div>
    <div class="col-md-2 well", id="progression-picture-capsule">
      Progression Album
    </div>
  </div>

  <div class="col-md-4">
    <% @capsule.mindmaps.each do |mindmap| %>
        <%= mindmap.src %>
        <strong><%= mindmap.src_purpose %></strong>
    <% end %>
  </div>
</div>
<%= link_to "See Capsule", capsule_path %>
<%= link_to "All Capsules", capsules_path %>
<%= link_to "Edit Capsule", edit_capsule_path %>
<%= link_to "Delete Capsule", capsule_path, method: :delete, data: {confirm: "Are you sure you want to delete the capsule"} %>
<%= link_to "Create Mindmap", new_mindmap_path %>
<%= link_to "Create Mindmap", new_comment_path %>